#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely, prints "I am invincible!!!" on SIGTERM
trap "echo 'I am invincible!!!'" SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
